config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :users, :controllers => {:confirmations => 'confirmations', :registrations => 'users' }

  devise_scope :user do
    patch "/confirm" => "confirmations#confirm"
  end
  resources :tunes
  resources :parts
  resources :users
  resources :groups
  resources :favorites
  resources :homeworks
  resources :messages
  resources :books do
   resources :chapters do
     resources :paragraphs
   end
  end
  resources :recordings
  resources :book_subscriptions
  resources :user_logs
  resources :annotations
  resources :questions
  resources :grooves

  root 'books#index'
  get 'practice' => "parts#practice", as: :tunes_practice
  get 'user_settings' => "home#user_settings", as: :user_settings
  get 'user_list' => "home#user_list", as: :user_list
  get 'interactive_excercises' => "home#interactive_excercises", as: :interactive_excercises
  get 'real_music' => "home#real_music", as: :real_music
  get 'pricing' => "home#pricing", as: :pricing
  get 'info' => "home#info", as: :info
  get 'pick_tune' => "tunes#pick", as: :pick_tune
  get 'parts/:id/add_favorite' => "parts#add_favorite", as: :add_favorite_part
  get 'parts/:id/remove_favorite' => "parts#remove_favorite", as: :remove_favorite_part
  post 'users/:id/select' => "users#select", as: :select_user
  post 'users/:id/take_over' => "users#take_over", as: :take_over_user
  post 'users/take_back' => "users#take_back", as: :take_back_user
  get 'tags/:tag', to: 'tunes#index', as: :tag
  put 'parts/update_hittimes/:id', to: 'parts#update_hittimes', as: :update_hittimes
  post 'parts/update_note_marks/:id', to: 'parts#update_note_marks', as: :update_note_marks
  delete 'annotations/delete_all_for_part/:part_id', to: 'annotations#destroy_all_for_part'
  get 'offline_favorites', to: 'favorites#offline_favorites'
  get 'offline_parts/:id', to: 'parts#offline'
  get 'serviceWorker.js', to: 'service_worker#index'
  get 'convert_to_scan/:id', to: 'parts#convert_to_scan'
  get 'groups/add_user/:id', to: 'groups#add_user', as: :group_add_user
  get 'groups/add_book/:id', to: 'groups#add_book', as: :group_add_book
  get 'timeline', to: 'recordings#current_user_timeline', as: :user_timeline
  get 'groups/:group_id/timeline', to: 'recordings#group_timeline', as: :group_timeline
  get 'students/:student_id/timeline', to: 'recordings#student_timeline', as: :student_timeline
  get 'parts/:id/assign_homework', to: 'parts#assign_homework', as: :assign_homework
  get 'parts/:id/remove_homework', to: 'parts#remove_homework', as: :remove_homework
  post 'questions/:id/check_answer', to: 'questions#check_answer'
  post 'comments/', to: 'comments#create'
  post 'parts/:id/youtube_links', to: 'parts#create_youtube_link', as: :youtube_links
  delete 'parts/:id/youtube_links/:youtube_link_id', to: 'parts#delete_youtube_link', as: :delete_youtube_link
  get 'questions/tagged_with/:tag', to: 'questions#tagged_with', as: :questions_tagged_with
  get 'parts/tagged_with/:tag', to: 'parts#tagged_with', as: :parts_tagged_with
  get 'part/:id/recordings', to: 'recordings#index', as: :part_recordings

end

app/models/recording.rb
class Recording < ActiveRecord::Base
  belongs_to :tune
  belongs_to :part
  belongs_to :user
  has_many :comments, as: :commentable

  mount_uploader :soundtrack, ::SoundtrackUploader
  ratyrate_rateable "performance"


  scope :for_user, -> (user) { where(:user_id => user.id) }

  def identifier
    "#{user.name} #{created_at.strftime("%d-%m-%Y")}"
  end

  def filename
    self.send(:attribute, "soundtrack") || self.id.to_s + ".mp3"
  end

  def soundtrack_base_file_name
    File.basename self.soundtrack.file.filename, ".*"
  end

  def speed_factors
    return [] if speed_versions.nil?
    speed_versions.split(',').each(&:strip!) - ['100']
  end

  def commentable_visit_url
    Rails.application.routes.url_helpers.part_url(self.part) + '#recordings'
  end

  def commentable_title
    "Commentaar"
  end

end

app/controllers/recordings_controller.rb
class RecordingsController < ApplicationController
  before_action :authenticate_user!

  def show

  end

  def index
    @part = Part.find(params[:id])
    @recordings = @part.recordings.paginate(per_page: 20, page: params[:page])
    respond_to do |format|
      format.js
    end
  end

  def create
    params.permit!
    if params[:audio]
      find_path_and_tune
      @recording = Recording.create(user_id: params[:user_id], part_id: params[:part_id], remarks: params[:remarks], access: params[:access])
      audio = params[:audio]
      audio.rewind
      File.open("#{save_path}.wav", 'wb') do |f|
        f.write params[:audio].read
      end
      %x[ffmpeg -i #{save_path}.wav #{save_path}.mp3 && rm -rf #{save_path}.wav}]
      %x[rm -rf #{save_path}.wav]
      @recording.update_attribute :soundtrack, "#{@part.id},mp3"
    elsif params[:recording]
      find_path_and_tune
      @recording = Recording.create(params[:recording])
      filename = @recording.soundtrack_base_file_name
      %x[ffmpeg -i public/audios/#{filename}.mp3 public/audios/#{filename}.wav]
      @recording.speed_factors.each do |factor|
        %x[rubberband public/audios/#{filename}.wav public/audios/#{filename}_#{factor}.wav -T 0.#{factor}]
        %x[ffmpeg -i public/audios/#{filename}_#{factor}.wav public/audios/#{filename}_#{factor}.mp3]
        %x[rm -rf public/audios/#{filename}_#{factor}.wav]
      end
      %x[rm -rf public/audios/#{filename}.wav]
    end
    @recordings = Recording.where(part_id: params[:part_id]).paginate(page: params[:page] || 1, per_page: 40)
    UserMailer.notify_upload(@recording).deliver_now unless @recording.user.teacher == nil
    respond_to do |format|
      format.html { redirect_to @part }
      format.js
    end
  end

  def update
    @recording = Recording.find(params[:id])
    respond_to do |format|
      format.json {
        render json: {result: "ok"}
      }
    end
  end

  def destroy
    @part = Part.find(params[:part_id])
    @recording = Recording.find(params[:id]).destroy
    @recordings = Recording.where(part_id: params[:part_id]).paginate(page: params[:page] || 1, per_page: 40)
    if @recording.soundtrack.file.nil? #recorded file
      %x[rm -rf #{save_path}.mp3]
    else #uploaded file
      @recording.speed_factors.each do |factor|
        %x[rm -rf public/audios/#{@recording.soundtrack_base_file_name}_#{factor}.mp3]
      end
    end

    redirect_to part_path @part
  end

  def current_user_timeline
    breadcrumbs
    @timeline_title = current_user.name
    @recordings = current_user.recordings.order('created_at desc').joins(:part).joins('INNER JOIN tunes on tunes.id = parts.tune_id')
    render 'recordings/timeline'
  end

  def group_timeline
    breadcrumbs
    @timeline_title = current_user.group.name
    @recordings = current_user.group.recordings(current_user)
    render 'recordings/timeline'
  end

  def student_timeline
    breadcrumbs
    student = User.find(params[:student_id])
    @timeline_title = student.name
    @recordings = current_user.student_recordings(student)
    render 'recordings/timeline'
  end


  private

  def find_path_and_tune
    @part = Part.find(params[:part_id])
    @tune = @part.tune
  end

  def save_path
    Rails.root.join("public/audios/#{@recording.id}")
  end

  def breadcrumbs
    @breadcrumbs =
        [
            { title: "books", link: root_url }
        ]
  end

end

app/views/recordings/_list.html.haml
.col-lg-12
  - for recording in @part.recordings.order("created_at desc")
    .row.recording.voffset10{class: recording.study_track ? 'study_track' : 'current'}
      .col-md-12.recording-container
        .row
          .col-md-4
            = recording.user.name
            = ", #{distance_of_time_in_words Time.now, recording.created_at} (#{recording.study_track ? t('recording.study_track') : t("instrument.#{@part.instrument}")})"
          .col-md-6
            = audio_tag recording.filename, id: "audio#{recording.id}", controls: true, preload: 'none'
          .col-md-1
            = link_to "<span class='glyphicon glyphicon-trash' aria-hidden='true'></span>".html_safe, recording_path(recording, part_id: @part.id), method: :delete
          .col-md-2
            = rating_for recording, 'performance', star_path: '/ratyrate', disable_after_rate: false, readonly: current_user.id != recording.user.teacher_id
        .row.recordingRemarks
          .col-md-6
            = "#{t("recording.remark")}: #{recording.remarks}"
        .col-lg-12
          .row.voffset10.list_comments{id: "comments_recording_#{recording.id}"}
            = render(partial: 'comments/list_comments', locals: {comments: recording.comments})
          = render(partial: 'comments/add_comment', locals: {commentable_type: 'Recording', commentable_id: recording.id})

  = will_paginate @recordings

:javascript
  maestoso.comments.init()

app/views/recordings/create.js.erb
<% recordings = escape_javascript(
  render(partial: 'parts/recordings')
) %>
<% modal_backings = escape_javascript(
  render(partial: 'parts/modal_backing')
) %>

$("#recordings").html("<%= recordings %>");
$("#modal_backings_container").html("<%= modal_backings %>");

app/views/recordings/index.js.erb
<% js = escape_javascript(
  render(partial: 'recordings/list')
) %>

$(".recordings_wrapper").html("<%= js %>");

app/views/recordings/timeline.html.haml
= render 'layouts/breadcrumb'
.row.timeline
  .col-md-12.timeline_container
    .row.timeline-header
      .col-md-12.timeline_title.container_title
        = t('recording.timeline')
        = @timeline_title
    - @recordings.each do |recording|
      .col-md-12.recording-container.voffset10
        .row
          .col-md-3
            = distance_of_time_in_words Time.now, recording.created_at
            = t('general.ago')

          .col-md-3
            = link_to recording.part.tune.title, tune_path(recording.part.tune)
        .row.voffset5
          .col-md-10
            = audio_tag recording.filename, controls: true
          .col-md-2
            = rating_for recording, 'performance', star_path: '/ratyrate', readonly: current_user.id != recording.user.teacher_id, disable_after_rate: false

        .row
          .col-md-12
            = "#{t("recording.remark")}: #{recording.remarks}"
        .row.voffset10.list_comments{id: "comments_recording_#{recording.id}"}
          = render(partial: 'comments/list_comments', locals: {comments: recording.comments})
        = render(partial: 'comments/add_comment', locals: {commentable_type: 'Recording', commentable_id: recording.id})

:javascript
  maestoso.comments.init()