config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :users, :controllers => {:confirmations => 'confirmations', :registrations => 'users' }

  devise_scope :user do
    patch "/confirm" => "confirmations#confirm"
  end
  resources :tunes
  resources :parts
  resources :users
  resources :groups
  resources :favorites
  resources :homeworks
  resources :messages
  resources :books do
   resources :chapters do
     resources :paragraphs
   end
  end
  resources :recordings
  resources :book_subscriptions
  resources :user_logs
  resources :annotations
  resources :questions
  resources :grooves

  root 'books#index'
  get 'practice' => "parts#practice", as: :tunes_practice
  get 'user_settings' => "home#user_settings", as: :user_settings
  get 'user_list' => "home#user_list", as: :user_list
  get 'interactive_excercises' => "home#interactive_excercises", as: :interactive_excercises
  get 'real_music' => "home#real_music", as: :real_music
  get 'pricing' => "home#pricing", as: :pricing
  get 'info' => "home#info", as: :info
  get 'pick_tune' => "tunes#pick", as: :pick_tune
  get 'parts/:id/add_favorite' => "parts#add_favorite", as: :add_favorite_part
  get 'parts/:id/remove_favorite' => "parts#remove_favorite", as: :remove_favorite_part
  post 'users/:id/select' => "users#select", as: :select_user
  post 'users/:id/take_over' => "users#take_over", as: :take_over_user
  post 'users/take_back' => "users#take_back", as: :take_back_user
  get 'tags/:tag', to: 'tunes#index', as: :tag
  put 'parts/update_hittimes/:id', to: 'parts#update_hittimes', as: :update_hittimes
  post 'parts/update_note_marks/:id', to: 'parts#update_note_marks', as: :update_note_marks
  delete 'annotations/delete_all_for_part/:part_id', to: 'annotations#destroy_all_for_part'
  get 'offline_favorites', to: 'favorites#offline_favorites'
  get 'offline_parts/:id', to: 'parts#offline'
  get 'serviceWorker.js', to: 'service_worker#index'
  get 'convert_to_scan/:id', to: 'parts#convert_to_scan'
  get 'groups/add_user/:id', to: 'groups#add_user', as: :group_add_user
  get 'groups/add_book/:id', to: 'groups#add_book', as: :group_add_book
  get 'timeline', to: 'recordings#current_user_timeline', as: :user_timeline
  get 'groups/:group_id/timeline', to: 'recordings#group_timeline', as: :group_timeline
  get 'students/:student_id/timeline', to: 'recordings#student_timeline', as: :student_timeline
  get 'parts/:id/assign_homework', to: 'parts#assign_homework', as: :assign_homework
  get 'parts/:id/remove_homework', to: 'parts#remove_homework', as: :remove_homework
  post 'questions/:id/check_answer', to: 'questions#check_answer'
  post 'comments/', to: 'comments#create'
  post 'parts/:id/youtube_links', to: 'parts#create_youtube_link', as: :youtube_links
  delete 'parts/:id/youtube_links/:youtube_link_id', to: 'parts#delete_youtube_link', as: :delete_youtube_link
  get 'questions/tagged_with/:tag', to: 'questions#tagged_with', as: :questions_tagged_with
  get 'parts/tagged_with/:tag', to: 'parts#tagged_with', as: :parts_tagged_with
  get 'part/:id/recordings', to: 'recordings#index', as: :part_recordings

end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :users
  has_many :book_subscriptions
  has_many :books, through: :book_subscriptions

  def self.for_user(user)
    return Group.order('name asc').all if user.role == 'admin'
    user.groups
  end

  def owner
    User.find(owner_id)
  end

  def recordings(current_user)
    Recording.joins('INNER JOIN users on users.id = recordings.user_id')
             .where(['users.group_id = ?', id])
             .where(["recordings.access = 'group' or users.id = ?", current_user.id])
             .order('created_at desc')
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_group, only: [:show, :edit, :update, :destroy, :add_user, :add_book]

  def index
    @groups = Group.for_user(current_user).paginate(per_page: 20, page: params[:page])
  end

  def show
    @users = @group.users
    @books = @group.books
  end

  def new
    @group = Group.new
  end

  def edit
  end

  def update
    params.permit!
    if params.keys.include?('user_id')
      User.find(params[:user_id]).update_attribute :group_id, @group.id
    elsif params.keys.include?('book_id')
      BookSubscription.create book_id: params[:book_id], group_id: @group.id
    else
      @group.update_attributes params[:group]
    end
    redirect_to @group
  end

  def create
    params.permit!
    @group  = Group.new(params[:group])
    @group.owner_id = current_user.id
    @group.save
    redirect_to group_url @group
  end

  def destroy
    @group.destroy
    redirect_to groups_url
  end

  def add_user
  end

  def add_book
  end

  private

  def find_group
    @group = Group.find(params[:id])
  end

end

app/views/groups/_form.html.haml
.form-group
  %label.col-sm-2.control-label{:for => "title"}
    = t('group.name')
  .col-sm-8
    = f.text_field :name, {class: "form-control"}
- if current_user.role == 'admin'
  .form-group
    %label.col-sm-2.control-label{:for => "owner"}
      = t('group.owner')
    .col-sm-8
      = f.select :owner_id, options_from_collection_for_select(User.teachers_and_admins, :id, :name, @group.owner_id), {class: "form-control"}
.form-group
  .col-sm-offset-2.col-sm-10
    %button{:type => "submit", :class=> "btn btn-info btn-default"}
      =t('group.save')

app/views/groups/_list.html.haml
%table.table.table-hover
  %thead
    %tr
      %th
        =t('group.name')
  %tbody{"data-link"=>"row"}
    -for group in @groups
      %tr
        %td
          = link_to group.name, group_path(group)
        %td
          - if current_user.may_update(group)
            =link_to "<span class='glyphicon glyphicon-trash' aria-hidden='true'></span>".html_safe, group_path(group), method: :delete

= will_paginate @groups

app/views/groups/add_book.html.haml
.row.voffset30.form-container
  %h4
    = t('group.add_book') + ': '
    = @group.name
  = form_for @group, :html => {class: "form-horizontal"} do |f|
    .form-group
      %label.col-sm-2.control-label{:for => "owner"}
        = t('book.title')
      .col-sm-8
        = select_tag :book_id, options_from_collection_for_select(current_user.books, :id, :title), {class: "form-control"}
    .form-group
      .col-sm-offset-2.col-sm-10
        %button{:type => "submit", :class=> "btn btn-info btn-default"}
          =t('general.ok')

app/views/groups/add_user.html.haml
.row.voffset30.form-container
  %h4
    = t('group.add_user') + ': '
    = @group.name
  = form_for @group, :html => {class: "form-horizontal"} do |f|
    .form-group
      %label.col-sm-2.control-label{:for => "owner"}
        = t('user.name')
      .col-sm-8
        = select_tag :user_id, options_from_collection_for_select(current_user.students, :id, :name), {class: "form-control"}
    .form-group
      .col-sm-offset-2.col-sm-10
        %button{:type => "submit", :class=> "btn btn-info btn-default"}
          =t('general.ok')

app/views/groups/edit.html.haml
.row.voffset30.form-container
  %h3
    Edit
  = form_for @group, :html => {class: "form-horizontal"} do |f|
    = render :partial => "form", locals:{ f: f }

app/views/groups/index.html.haml
.row.content_container
  .col-md-12
    .row.list_filters
      .row
        .col-lg-12
          .buttons
            - if current_user.may_create(Group)
              = link_to(t('group.new'), new_group_url, {:class => "btn btn-info voffset15"})
    =render partial: 'list'

app/views/groups/new.html.haml
.row.voffset30.form-container
  %h3
    =t('group.new')
  = form_for @group, :html => {class: "form-horizontal"} do |f|
    = render :partial => "form", locals:{ f: f }

app/views/groups/show.html.haml
.row.content_container
  .col-md-12
    - if current_user && current_user.may_update(@group)
      .row
        .buttons
          = link_to(t("group.edit"), edit_group_url(@group), { :class => "btn btn-info voffset15" })
          = link_to(t('group.add_user'), group_add_user_url(@group), {:class => "btn btn-info voffset15"})
          = link_to(t('group.add_book'), group_add_book_url(@group), {:class => "btn btn-info voffset15"})

    %ul.nav.nav-tabs.simple_form.voffset15{:role => "tablist"}
      %li.active{:role => "presentation"}
        %a{"aria-controls" => "General info", "data-toggle" => "tab", :href => "#general_info", :role => "tab"} #{t('group.general_info')}
      %li{:role => "presentation"}
        %a{"aria-controls" => "Books", "data-toggle" => "tab", :href => "#students", :role => "tab"} #{t('group.students')}
      %li{:role => "presentation"}
        %a{"aria-controls" => "Books", "data-toggle" => "tab", :href => "#books", :role => "tab"} #{t('group.books')}

    .tab-content
      #general_info.tab-pane.active{:role => "tabpanel"}
        .row.voffset30
          .col-md-2
            %label.col-sm-2.control-label
              =t('group.name')
          .col-md-4
            = @group.name
        .row.voffset15
          .col-md-2
            %label.col-sm-2.control-label
              =t('group.owner')
          .col-md-4
            = @group.owner.name

      #students.tab-pane{:role => "tabpanel"}
        .row.voffset30
          .col-md-12
            = render('users/list')

      #books.tab-pane{:role => "tabpanel"}
        .row.voffset30
          .col-md-12
            %table.table.table-hover#filterrific_results
              %thead
                %tr
                  %th
                    =t("book.title")
              %tbody{"data-link"=>"row"}
                -for book in @books
                  %tr
                    %td
                      = book.title