config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :users, :controllers => {:confirmations => 'confirmations', :registrations => 'users' }

  devise_scope :user do
    patch "/confirm" => "confirmations#confirm"
  end
  resources :tunes
  resources :parts
  resources :users
  resources :groups
  resources :favorites
  resources :homeworks
  resources :messages
  resources :books do
   resources :chapters do
     resources :paragraphs
   end
  end
  resources :recordings
  resources :book_subscriptions
  resources :user_logs
  resources :annotations
  resources :questions
  resources :grooves

  root 'books#index'
  get 'practice' => "parts#practice", as: :tunes_practice
  get 'user_settings' => "home#user_settings", as: :user_settings
  get 'user_list' => "home#user_list", as: :user_list
  get 'interactive_excercises' => "home#interactive_excercises", as: :interactive_excercises
  get 'real_music' => "home#real_music", as: :real_music
  get 'pricing' => "home#pricing", as: :pricing
  get 'info' => "home#info", as: :info
  get 'pick_tune' => "tunes#pick", as: :pick_tune
  get 'parts/:id/add_favorite' => "parts#add_favorite", as: :add_favorite_part
  get 'parts/:id/remove_favorite' => "parts#remove_favorite", as: :remove_favorite_part
  post 'users/:id/select' => "users#select", as: :select_user
  post 'users/:id/take_over' => "users#take_over", as: :take_over_user
  post 'users/take_back' => "users#take_back", as: :take_back_user
  get 'tags/:tag', to: 'tunes#index', as: :tag
  put 'parts/update_hittimes/:id', to: 'parts#update_hittimes', as: :update_hittimes
  post 'parts/update_note_marks/:id', to: 'parts#update_note_marks', as: :update_note_marks
  delete 'annotations/delete_all_for_part/:part_id', to: 'annotations#destroy_all_for_part'
  get 'offline_favorites', to: 'favorites#offline_favorites'
  get 'offline_parts/:id', to: 'parts#offline'
  get 'serviceWorker.js', to: 'service_worker#index'
  get 'convert_to_scan/:id', to: 'parts#convert_to_scan'
  get 'groups/add_user/:id', to: 'groups#add_user', as: :group_add_user
  get 'groups/add_book/:id', to: 'groups#add_book', as: :group_add_book
  get 'timeline', to: 'recordings#current_user_timeline', as: :user_timeline
  get 'groups/:group_id/timeline', to: 'recordings#group_timeline', as: :group_timeline
  get 'students/:student_id/timeline', to: 'recordings#student_timeline', as: :student_timeline
  get 'parts/:id/assign_homework', to: 'parts#assign_homework', as: :assign_homework
  get 'parts/:id/remove_homework', to: 'parts#remove_homework', as: :remove_homework
  post 'questions/:id/check_answer', to: 'questions#check_answer'
  post 'comments/', to: 'comments#create'
  post 'parts/:id/youtube_links', to: 'parts#create_youtube_link', as: :youtube_links
  delete 'parts/:id/youtube_links/:youtube_link_id', to: 'parts#delete_youtube_link', as: :delete_youtube_link
  get 'questions/tagged_with/:tag', to: 'questions#tagged_with', as: :questions_tagged_with
  get 'parts/tagged_with/:tag', to: 'parts#tagged_with', as: :parts_tagged_with
  get 'part/:id/recordings', to: 'recordings#index', as: :part_recordings

end

app/models/user.rb
class User < ActiveRecord::Base
  include ::Authorization
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  has_many :favorites
  has_many :homeworks
  has_many :recordings
  has_many :book_subscriptions
  has_many :personal_books, class_name: 'Book', through: :book_subscriptions
  has_many :books, as: :group_books, through: :groups
  has_many :user_logs
  has_many :medals
  has_many :groups, foreign_key: :owner_id
  belongs_to :group
  ratyrate_rater

  filterrific(
    default_filter_params: { sorted_by: 'last_name' },
    available_filters: [
    :search,
    :sorted_by
    ]
  )

  scope :with_role, ->(role) { where(:role => role) }
  #scope :search, ->(search) { where(['lower(last_name) like :search or lower(first_name) like :search or lower(email) like :search', :search =>"%#{search.downcase}%"] ) }
  scope :sorted_by, ->(column) { order(column) }
  scope :search, -> (l) { where(["lower(last_name) like ?", "%#{l.downcase}%"]) }
  scope :group_users, -> (user) { where(group_id: user.group_id) }
  scope :teachers_and_admins, -> () { where("role in ('teacher', 'admin')")}

  def password_required?
    super if confirmed?
  end

  def password_match?
    self.errors[:password] << t('user.password_blank') if password.blank?
    self.errors[:password_confirmation] << t('user.password_confirmation_blank') if password_confirmation.blank?
    self.errors[:password_confirmation] << t('user.password_confirmation_match') if password != password_confirmation
    password == password_confirmation && !password.blank?
  end

  def name
    if [first_name, last_name].include? nil
      email
    else
      "#{first_name} #{last_name}"
    end
  end

  def username
    "#{first_name}_#{last_name}".gsub(" ", "_").downcase
  end

  def students
    return nil unless ['teacher', 'admin'].include? role
    return User.all if role == 'admin'
    User.where(teacher_id: id)
  end

  def books
    return Book.all if role == 'admin'
    if role == 'teacher'
      written_books = Book.where(author_id: id).all
      instrument_books = Book.where(instrument: instrument).all
      written_books + instrument_books
    else
      # TODO student
    end
  end

  def teacher
    return nil if teacher_id.nil?
    User.where(id: teacher_id).first
  end

  def log_event(activity, part, message)
    todays_log = user_logs.where(activity: activity).where(date: Date.today).first
    todays_log = UserLog.new(activity: activity, user_id: self.id, part_id: part.try(:id), date: Date.today) if todays_log.nil?
    todays_log.events = todays_log.events.to_s + "<br>" + message
    todays_log.save
  end

  def grouped_medals
    medals.where(status: 'earned').group(:color).count(:color)
  end

  def student_recordings(student)
    return [] unless ['admin', 'teacher'].include?(role)
    return [] unless student.teacher_id == id
    student.recordings.where("access IN ('group', 'teacher')")#.order('created_at desc')
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:new, :create]

  def index
    if current_user.role == "teacher"
      scope = User.where teacher_id: current_user
    elsif current_user.role == "admin"
      unless params["role"].nil? || params[:role] == ""
        scope = User.where(role: params[:role])
      else
        scope = User
      end
    else
      scope = User.nil
    end
    puts "scope: count=#{scope.count}"
    #@filterrific = initialize_filterrific(scope,params[:filterrific]) or return
    #@users = @filterrific.find.page(params[:page])
    @filterrific = initialize_filterrific(scope.order(:last_name),params[:filterrific]) or return
    @users = @filterrific.find.page(params[:page])

  end

  def show
   @user = User.find params[:id]
   if current_user.role == "admin" || (current_user.role == "teacher" && @user.teacher_id == current_user.id)
     @subscriptions = @user.book_subscriptions.paginate(page: params[:page], per_page: 40)
     @homeworks = Homework.for_user(@user).paginate(page: params[:page], per_page: 40)
     @recordings = Recording.for_user(@user).where('study_track is not true').order('created_at desc').paginate(page: params[:page], per_page: 40)
     @user_logs = @user.user_logs
     @users = @user.students if current_user.role == "admin"
   else
     render :text => "No access..."
   end

  end

  def new
    @user = User.new group_id: params[:group_id]
  end

  def edit
    @user = User.find params[:id]
  end

  def update
    @user = User.find params[:id]
    @user.update_attributes params[:user].permit!
    redirect_to users_url(@user, role: params[:role])
  end

  def create
    # if a teacher creates a user he/she is the users teacher
    @user = User.create(email: params[:user][:email],
                        password: params[:user][:password],
                        password_confirmation: params[:user][:password_confirmation],
                        first_name: params[:user][:first_name],
                        last_name: params[:user][:last_name],
                        instrument: params[:user][:instrument],
                        part_number: params[:user][:part_number],
                        role: set_role(params[:user][:role]),
                        teacher_id: set_teacher(params[:user][:teacher_id]),
                        group_id: set_group(params[:user][:group_id]))

    redirect_to users_url
  end

  def destroy
    User.find(params[:id]).destroy
    redirect_to users_url
  end

  def new_book_subscription
  end

  def select
    session[:current_student] = User.find(params[:id])
    redirect_to :users
  end

  def take_over
    @user = User.find(params[:id])
    if current_user.may_take_over(@user)
      session[:overtaking_user] = current_user
      sign_in(User.find(params[:id]))
    end
    redirect_to "/"
  end

  def take_back
    unless session[:overtaking_user].nil?
      sign_in(User.find(session[:overtaking_user]["id"]))
      session[:overtaking_user] = nil
    end
    redirect_to :users
  end

  private

  def set_role(role)
    if current_user && current_user.role == 'admin'
      role = role || "teacher"
    elsif current_user && current_user.role == 'teacher'
      role = 'student'
    else
      role = 'student'
    end
    return role
  end

  def set_teacher(teacher)
    if current_user && current_user.role == 'admin'
      teacher = teacher
    elsif current_user && current_user.role == 'teacher'
      teacher = current_user.id
    else
      teacher = nil
    end
    return teacher
  end

  def set_group(group)
    if current_user && current_user.role == 'admin'
      group = group
    elsif current_user && current_user.role == 'teacher'
      group = current_user.group.id
    else
      group = nil
    end
    return group
  end

end

app/views/users/_activity.html.haml
%table.table.table-hover
  %thead
    %tr
      %th
        Date
      %th
        Activity        
  %tbody{"data-link"=>"row"}
    -for log in @user_logs
      %tr
        %td
          = link_to log.date.strftime("%d-%m-%Y"), user_log_path(log), {:data=> {:remote => true, :target=>"#popup", :toggle=>"modal"}}
        %td
          = log.activity  

app/views/users/_form.html.haml
= form_for @user, :html => { class: 'form-horizontal'} do |f|
  =hidden_field_tag :role, params[:role]
  =f.hidden_field :group_id
  .form-group
    %label.col-sm-2.control-label{ for: 'email' }
      =t("user.email")
    .col-sm-8
      = f.text_field :email, { class: 'form-control' }
  .form-group
    %label.col-sm-2.control-label{ for:  'last_name' }
      = t('user.last_name')
    .col-sm-8
      = f.text_field :last_name, { class: 'form-control' }
  .form-group
    %label.col-sm-2.control-label{ for: 'first_name' }
      = t('user.first_name')
    .col-sm-8
      = f.text_field :first_name, { class: 'form-control'}
  .form-group
    %label.col-sm-2.control-label{ for:  'instrument'}
      = t('part.instrument')
    .col-sm-8
      = f.select :instrument, options_for_select(instruments, @user.instrument), { class: 'form-control'}
  .form-group
    %label.col-sm-2.control-label{ for: 'part_number'}
      = t('part.part_number')
    .col-sm-8
      = f.text_field :part_number, { class: 'form-control'}

  - if current_user.role == 'admin'
    .form-group
      %label.col-sm-2.control-label{ for: 'teacher_id'}
        =t("user.teacher")
      .col-sm-8
        = f.select :teacher_id, options_from_collection_for_select(User.all, :id, :name, @user.teacher_id), { include_blank: true, class: 'form-control' }
    .form-group
      %label.col-sm-2.control-label{ for: 'role'}
        =t("user.role")
      .col-sm-8
        = f.select :role, options_for_select(%w(admin teacher student), @user.role), { class: 'form-control'}
    .form-group
      %label.col-sm-2.control-label{ for: 'group_id'}
        =t("user.group")
      .col-sm-8
        = f.select :group_id, options_from_collection_for_select(Group.all, :id, :name), { class: 'form-control'}

  - if @user.role == 'teacher'
    .form-group
      %label.col-sm-2.control-label{ for: 'teacher_instruments'}
        =t("user.teacher_instruments")
      .col-sm-8
        = f.select :teacher_instruments, options_for_select(instruments), { class: 'form-control'}, { :multiple => true, :size => 5 }

  .form-group
    .col-sm-offset-2.col-sm-10
      %button{type: 'submit', class: 'btn btn-default'}
        =t('user.save')

app/views/users/_general_info.html.haml
.row.voffset15
  .col-md-2
    %label.col-sm-2.control-label
      =t('user.email')
  .col-md-4
    = @user.email
.row.voffset15
  .col-md-2
    %label.col-sm-2.control-label
      =t('user.username')
  .col-md-4
    = @user.username
.row.voffset15
  .col-md-2
    %label.col-sm-2.control-label
      =t('user.last_name')
  .col-sm-8
    = @user.last_name
.row.voffset15
  .col-md-2
    %label.col-sm-2.control-label
      =t("user.first_name")
  .col-sm-8
    = @user.first_name
.row.voffset15
  .col-md-2
    %label.col-sm-2.control-label
      = t('part.instrument')
  .col-sm-8
    = @user.instrument
.row.voffset15
  .col-md-2
    %label.col-sm-2.control-label
      = t('part.part_number')
  .col-sm-8
    = @user.part_number
- if @user.role == 'student'
  .row.voffset15
    .col-md-2
      %label.col-sm-2.control-label
        = t('user.teacher')
    .col-sm-8
      = @user.teacher.name

app/views/users/_list.html.haml
%table.table.table-hover#filterrific_results
  %thead
    %tr
      %th
        =t("user.email")
      %th
        =t("user.last_name")
      %th
        =t("user.first_name")
      - if params[:role].nil?
        %th
          =t("user.role")
      %th

  %tbody{"data-link"=>"row"}
    -for user in @users
      %tr
        %td
          = link_to user.email, user_path(user, role: params[:role])
        %td
          = user.last_name
        %td
          = user.first_name
        - if params[:role].nil?
          %td
            = user.role
        %td
          = link_to t("user.select"), select_user_url(user.id), method: :post, class: "btn btn-sm btn-transparent"
        %td
          -if current_user.may_take_over(user)
            = link_to t("user.take_over"), take_over_user_url(user.id), method: :post, class: "btn btn-sm btn-transparent"
        %td
          - if current_user.may_update(user)
            = link_to "<span class='glyphicon glyphicon-trash' aria-hidden='true'></span>".html_safe, user_path(user), method: :delete

app/views/users/_tabs_admin.html.haml
%ul.nav.nav-tabs.simple_form{:role => "tablist"}
  %li.active{:role => "presentation"}
    %a{"aria-controls" => "General info", "data-toggle" => "tab", :href => "#general_info", :role => "tab"} #{t('user.general_info')}
  %li{:role => "presentation"}
    %a{"aria-controls" => "Students", "data-toggle" => "tab", :href => "#students", :role => "tab"} #{t('user.students')}
  %li{:role => "presentation"}
    %a{"aria-controls" => "Books", "data-toggle" => "tab", :href => "#books", :role => "tab"} #{t('nav.books')}

.tab-content
  #general_info.tab-pane.active{:role => "tabpanel"}
    = render partial: 'general_info'
  #books.tab-pane{:role => "tabpanel"}
    .row.voffset15
      .col-md-12.loffset10
        = render partial: 'book_subscriptions/list'

app/views/users/_tabs_student.html.haml
%ul.nav.nav-tabs.simple_form{:role => "tablist"}
  %li.active{:role => "presentation"}
    %a{"aria-controls" => "General info", "data-toggle" => "tab", :href => "#general_info", :role => "tab"} #{t('user.general_info')}
  %li{:role => "presentation"}
    %a{"aria-controls" => "Books", "data-toggle" => "tab", :href => "#books", :role => "tab"} #{t('nav.books')}
  %li{:role => "presentation"}
    %a{"aria-controls" => "Homework", "data-toggle" => "tab", :href => "#homework", :role => "tab"} #{t('homework.homework')}
/ Tab panes
.tab-content
  #general_info.tab-pane.active{:role => "tabpanel"}
    = render partial: 'general_info'
  #books.tab-pane{:role => "tabpanel"}
    .row.voffset15
      .col-md-12.loffset10
        = render partial: 'book_subscriptions/list'
  #homework.tab-pane{:role => "tabpanel"}
    .row.voffset15
      .col-md-12.loffset10
        = render partial: 'homeworks/list'

app/views/users/_tabs_teacher.html.haml
%ul.nav.nav-tabs.simple_form{:role => "tablist"}
  %li.active{:role => "presentation"}
    %a{"aria-controls" => "General info", "data-toggle" => "tab", :href => "#general_info", :role => "tab"} #{t('user.general_info')}
  %li{:role => "presentation"}
    %a{"aria-controls" => "Students", "data-toggle" => "tab", :href => "#students", :role => "tab"} #{t('user.students')}
  %li{:role => "presentation"}
    %a{"aria-controls" => "Books", "data-toggle" => "tab", :href => "#books", :role => "tab"} #{t('nav.books')}
.tab-content
  #general_info.tab-pane.active{:role => "tabpanel"}
    = render partial: 'general_info'
  #students.tab-pane{:role => "tabpanel"}
    .row.voffset15
      .col-md-12.loffset10
        = render partial: 'users/list'
  #books.tab-pane{:role => "tabpanel"}
    .row.voffset15
      .col-md-12.loffset10
        = render partial: 'book_subscriptions/list'

app/views/users/edit.html.haml
.row.voffset30.form-container
  %h3
    = t("edit_user")
  = render partial: "form"

app/views/users/index.html.haml
.row.content_container
  .col-md-12
    .row.list_filters
      .row
        .col-lg-12
          .buttons
            = link_to(t("user.new_#{params[:role]}"), new_user_url(role: params[:role]), {:class => "btn btn-info voffset15"})
      = form_for_filterrific @filterrific do |f|
        = hidden_field_tag :role, params[:role]
        .row.voffset10
          .col-md-12
            %label
            = f.text_field :search, class: 'filterrific-periodically-observed search', placeholder: t('user.search')
        %div
    = render_filterrific_spinner
    = render "list"

app/views/users/index.js.erb
<% js = escape_javascript(
  render(partial: 'users/list', locals: { users: @users })
) %>
$("#filterrific_results").html("<%= js %>");

app/views/users/new.html.haml
.row.voffset30.form-container
  %h3
    =t("user.new")
  = render partial: "form"      

app/views/users/show.html.haml
.row.content_container
  .col-md-12
    .row
      .buttons
        = link_to(t('user.edit'), edit_user_url(@user, role: params[:role]), { :class => "btn btn-info voffset15" })
        = link_to(t('user.subscribe_book'), new_book_subscription_url(user_id: @user.id), { :class => "btn btn-info voffset15" })

    .voffset15
      / Nav tabs
      =render "tabs_#{@user.role}"